/** Generated by scripts/gen-note-audio-assets.mjs — do not edit manually. */
import { FeedbackSound } from './noteAudioCatalog';

export const NOTE_AUDIO_MODULES: Record<string, number> = {
  'c1t0': require('../../../assets/audio/notes/c1t0.mp3'),
  'c1t1': require('../../../assets/audio/notes/c1t1.mp3'),
  'c1t10': require('../../../assets/audio/notes/c1t10.mp3'),
  'c1t11': require('../../../assets/audio/notes/c1t11.mp3'),
  'c1t12': require('../../../assets/audio/notes/c1t12.mp3'),
  'c1t13': require('../../../assets/audio/notes/c1t13.mp3'),
  'c1t14': require('../../../assets/audio/notes/c1t14.mp3'),
  'c1t15': require('../../../assets/audio/notes/c1t15.mp3'),
  'c1t16': require('../../../assets/audio/notes/c1t16.mp3'),
  'c1t17': require('../../../assets/audio/notes/c1t17.mp3'),
  'c1t18': require('../../../assets/audio/notes/c1t18.mp3'),
  'c1t19': require('../../../assets/audio/notes/c1t19.mp3'),
  'c1t2': require('../../../assets/audio/notes/c1t2.mp3'),
  'c1t3': require('../../../assets/audio/notes/c1t3.mp3'),
  'c1t4': require('../../../assets/audio/notes/c1t4.mp3'),
  'c1t5': require('../../../assets/audio/notes/c1t5.mp3'),
  'c1t6': require('../../../assets/audio/notes/c1t6.mp3'),
  'c1t7': require('../../../assets/audio/notes/c1t7.mp3'),
  'c1t8': require('../../../assets/audio/notes/c1t8.mp3'),
  'c1t9': require('../../../assets/audio/notes/c1t9.mp3'),
  'c2t0': require('../../../assets/audio/notes/c2t0.mp3'),
  'c2t1': require('../../../assets/audio/notes/c2t1.mp3'),
  'c2t2': require('../../../assets/audio/notes/c2t2.mp3'),
  'c2t3': require('../../../assets/audio/notes/c2t3.mp3'),
  'c2t4': require('../../../assets/audio/notes/c2t4.mp3'),
  'c3t0': require('../../../assets/audio/notes/c3t0.mp3'),
  'c3t1': require('../../../assets/audio/notes/c3t1.mp3'),
  'c3t2': require('../../../assets/audio/notes/c3t2.mp3'),
  'c3t3': require('../../../assets/audio/notes/c3t3.mp3'),
  'c3t4': require('../../../assets/audio/notes/c3t4.mp3'),
  'c4t0': require('../../../assets/audio/notes/c4t0.mp3'),
  'c4t1': require('../../../assets/audio/notes/c4t1.mp3'),
  'c4t2': require('../../../assets/audio/notes/c4t2.mp3'),
  'c4t3': require('../../../assets/audio/notes/c4t3.mp3'),
  'c4t4': require('../../../assets/audio/notes/c4t4.mp3'),
  'c5t0': require('../../../assets/audio/notes/c5t0.mp3'),
  'c5t1': require('../../../assets/audio/notes/c5t1.mp3'),
  'c5t2': require('../../../assets/audio/notes/c5t2.mp3'),
  'c5t3': require('../../../assets/audio/notes/c5t3.mp3'),
  'c5t4': require('../../../assets/audio/notes/c5t4.mp3'),
  'c6t0': require('../../../assets/audio/notes/c6t0.mp3'),
  'c6t1': require('../../../assets/audio/notes/c6t1.mp3'),
  'c6t2': require('../../../assets/audio/notes/c6t2.mp3'),
  'c6t3': require('../../../assets/audio/notes/c6t3.mp3'),
  'c6t4': require('../../../assets/audio/notes/c6t4.mp3'),
};

export const FEEDBACK_AUDIO_MODULES: Record<FeedbackSound, number> = {
  correct: require('../../../assets/audio/feedback/correct.mp3'),
  wrong: require('../../../assets/audio/feedback/wrong.mp3'),
  tap: require('../../../assets/audio/feedback/tap.mp3'),
};

export function getNoteAudioModule(key: string): number | undefined {
  return NOTE_AUDIO_MODULES[key];
}

export function getFeedbackAudioModule(kind: FeedbackSound): number {
  return FEEDBACK_AUDIO_MODULES[kind];
}
